name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: [ macos-latest ]
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn gulp bower
    - env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        yarn install
        bower install
        cd bower_components/jsoneditor
        npm install
        npm run build
        cd ../../
        gulp js.libs css.libs assets.libs
        yarn test --reporter mochawesome
        yarn make
    - name: Upload test results
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Test report
        path: mochawesome-report
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Mac OS X files
        path: out/make
